---
# Connect to AWS ECS
- name: Start AWS ECS service
  hosts: localhost
  connection: local
  gather_facts: False
  
  # load variables from vars file
  vars:
  - vars/all
  
  tasks:
  - name: Launch EC2
    ec2:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      instance_tags:
        Name: EC2_ansible_poc
      count: "{{ ec2_instance_count }}"
      wait: true
    register: ec2
