---
# Connect to AWS ECS
- name: Start AWS ECS service
  hosts: localhost
  connection: local
  gather_facts: False
  
  # load variables from vars file
  vars:
  - vars/all
  
  tasks:
  - name: Run task
    ecs_task:
      operation: run
      cluster: default
      task_definition: ansible-continuous-delivery
      count: 1
    register: task_output
